import { IncidentObservation, IncidentScenario } from './domain';

const source = (id: string, label: string) => ({
  id,
  label,
  provenance: 'synthetic' as const,
  access: 'read-only' as const,
});

const observation = (
  value: Omit<IncidentObservation, 'source'> & {
    source: ReturnType<typeof source>;
  },
): IncidentObservation => value;

const pvInverterBlockDerating: IncidentScenario = {
  schemaVersion: '1.0',
  id: 'synthetic-pv-inverter-block-derating',
  title: 'PV inverter-block derating',
  description:
    'Synthetic localized PV production deviation with a read-only inverter alarm and healthy peer-block telemetry.',
  synthetic: true,
  analysisAsOf: '2026-06-18T14:00:00-04:00',
  asset: {
    id: 'DEMO-PV-SITE-01',
    label: 'Synthetic PV Site 01',
    kind: 'pv',
    capacityMw: 48,
    bessCapacityMwh: null,
  },
  window: {
    start: '2026-06-18T11:00:00-04:00',
    end: '2026-06-18T14:00:00-04:00',
  },
  observations: [
    observation({
      id: 'pv-derating-expected-block-power',
      kind: 'telemetry',
      observedAt: '2026-06-18T13:55:00-04:00',
      assetId: 'DEMO-INV-BLOCK-07',
      signal: 'pv.expected_power_mw',
      value: 8.4,
      unit: 'MW',
      quality: 'valid',
      source: source('DEMO-MODEL-01', 'Synthetic expected-power model'),
      statement: 'Expected block power is 8.4 MW for the current synthetic conditions.',
    }),
    observation({
      id: 'pv-derating-actual-block-power',
      kind: 'telemetry',
      observedAt: '2026-06-18T13:55:00-04:00',
      assetId: 'DEMO-INV-BLOCK-07',
      signal: 'pv.actual_power_mw',
      value: 4.9,
      unit: 'MW',
      quality: 'valid',
      source: source('DEMO-LOGGER-07', 'Synthetic inverter logger'),
      statement: 'Measured block power is 4.9 MW in the read-only synthetic sample.',
    }),
    observation({
      id: 'pv-derating-alarm',
      kind: 'alarm',
      observedAt: '2026-06-18T11:04:00-04:00',
      assetId: 'DEMO-INV-BLOCK-07',
      signal: 'inverter.alarm_code',
      value: 'DERATING_ACTIVE',
      unit: 'state',
      quality: 'valid',
      source: source('DEMO-LOGGER-07', 'Synthetic inverter logger'),
      statement: 'The synthetic inverter logger reports alarm code DERATING_ACTIVE.',
    }),
    observation({
      id: 'pv-derating-irradiance',
      kind: 'weather',
      observedAt: '2026-06-18T13:55:00-04:00',
      assetId: 'DEMO-METEO-01',
      signal: 'weather.irradiance_wm2',
      value: 910,
      unit: 'W/m2',
      quality: 'valid',
      source: source('DEMO-METEO-01', 'Synthetic weather station'),
      statement: 'Synthetic plane-of-array irradiance is 910 W/m2.',
    }),
    observation({
      id: 'pv-derating-peer-block-power',
      kind: 'telemetry',
      observedAt: '2026-06-18T13:55:00-04:00',
      assetId: 'DEMO-INV-BLOCK-08',
      signal: 'pv.peer_block_power_mw',
      value: 8.2,
      unit: 'MW',
      quality: 'valid',
      source: source('DEMO-LOGGER-08', 'Synthetic peer inverter logger'),
      statement: 'Comparable peer block power is 8.2 MW in the same synthetic interval.',
    }),
    observation({
      id: 'pv-derating-dc-string-current-gap',
      kind: 'data-quality',
      observedAt: '2026-06-18T14:00:00-04:00',
      assetId: 'DEMO-INV-BLOCK-07',
      signal: 'pv.dc_string_current_a',
      value: null,
      unit: 'A',
      quality: 'missing',
      source: source('DEMO-LOGGER-07', 'Synthetic inverter logger'),
      statement: 'DC string-current detail is not included in this synthetic sample.',
    }),
  ],
};
const ambiguousPvUnderperformance: IncidentScenario = {
  schemaVersion: '1.0',
  id: 'synthetic-ambiguous-pv-underperformance',
  title: 'Ambiguous PV underperformance',
  description:
    'Synthetic plant-level underperformance with suspect irradiance, incomplete soiling evidence, and no active inverter alarm.',
  synthetic: true,
  analysisAsOf: '2026-06-19T15:00:00-04:00',
  asset: {
    id: 'DEMO-PV-SITE-02',
    label: 'Synthetic PV Site 02',
    kind: 'pv',
    capacityMw: 40,
    bessCapacityMwh: null,
  },
  window: {
    start: '2026-06-19T12:00:00-04:00',
    end: '2026-06-19T15:00:00-04:00',
  },
  observations: [
    observation({
      id: 'pv-ambiguous-expected-power',
      kind: 'telemetry',
      observedAt: '2026-06-19T14:55:00-04:00',
      assetId: 'DEMO-PV-SITE-02',
      signal: 'pv.expected_power_mw',
      value: 32,
      unit: 'MW',
      quality: 'valid',
      source: source('DEMO-MODEL-02', 'Synthetic expected-power model'),
      statement: 'Expected plant power is 32 MW for the synthetic interval.',
    }),
    observation({
      id: 'pv-ambiguous-actual-power',
      kind: 'telemetry',
      observedAt: '2026-06-19T14:55:00-04:00',
      assetId: 'DEMO-PV-SITE-02',
      signal: 'pv.actual_power_mw',
      value: 23,
      unit: 'MW',
      quality: 'valid',
      source: source('DEMO-POI-METER-02', 'Synthetic POI meter'),
      statement: 'Measured plant power is 23 MW in the read-only synthetic sample.',
    }),
    observation({
      id: 'pv-ambiguous-pr',
      kind: 'telemetry',
      observedAt: '2026-06-19T14:55:00-04:00',
      assetId: 'DEMO-PV-SITE-02',
      signal: 'pv.performance_ratio_pct',
      value: 71,
      unit: '%',
      quality: 'valid',
      source: source('DEMO-ANALYTICS-02', 'Synthetic performance calculation'),
      statement: 'Calculated performance ratio is 71% for the synthetic sample window.',
    }),
    observation({
      id: 'pv-ambiguous-irradiance',
      kind: 'weather',
      observedAt: '2026-06-19T14:55:00-04:00',
      assetId: 'DEMO-METEO-02',
      signal: 'weather.irradiance_wm2',
      value: 760,
      unit: 'W/m2',
      quality: 'suspect',
      source: source('DEMO-METEO-02', 'Synthetic weather station'),
      statement: 'Reported synthetic irradiance is 760 W/m2 and is flagged suspect.',
    }),
    observation({
      id: 'pv-ambiguous-cleaning-note',
      kind: 'maintenance-note',
      observedAt: '2026-06-17T16:00:00-04:00',
      assetId: 'DEMO-PV-SITE-02',
      signal: 'maintenance.cleaning_completed',
      value: true,
      unit: 'boolean',
      quality: 'valid',
      source: source('DEMO-CMMS-02', 'Synthetic maintenance log'),
      statement: 'The synthetic maintenance log records cleaning completed two days earlier.',
    }),
    observation({
      id: 'pv-ambiguous-alarm-clear',
      kind: 'alarm',
      observedAt: '2026-06-19T14:55:00-04:00',
      assetId: 'DEMO-PV-SITE-02',
      signal: 'inverter.alarm_code',
      value: 'NONE',
      unit: 'state',
      quality: 'valid',
      source: source('DEMO-LOGGER-02', 'Synthetic inverter fleet logger'),
      statement: 'No active inverter alarm is present in the synthetic alarm list.',
    }),
    observation({
      id: 'pv-ambiguous-soiling-gap',
      kind: 'data-quality',
      observedAt: '2026-06-19T15:00:00-04:00',
      assetId: 'DEMO-PV-SITE-02',
      signal: 'pv.soiling_index_pct',
      value: null,
      unit: '%',
      quality: 'missing',
      source: source('DEMO-SOILING-02', 'Synthetic soiling reference'),
      statement: 'No soiling index is available in the synthetic scenario.',
    }),
    observation({
      id: 'pv-ambiguous-reference-gap',
      kind: 'data-quality',
      observedAt: '2026-06-19T15:00:00-04:00',
      assetId: 'DEMO-METEO-REF-02',
      signal: 'weather.reference_irradiance_wm2',
      value: null,
      unit: 'W/m2',
      quality: 'missing',
      source: source('DEMO-METEO-REF-02', 'Synthetic independent weather reference'),
      statement: 'Independent reference irradiance is not included in the synthetic scenario.',
    }),
  ],
};

const bessEmsMeterMismatch: IncidentScenario = {
  schemaVersion: '1.0',
  id: 'synthetic-bess-ems-meter-mismatch',
  title: 'BESS EMS-versus-meter mismatch',
  description:
    'Synthetic disagreement between EMS telemetry and an independent read-only meter without thermal or BMS alarms.',
  synthetic: true,
  analysisAsOf: '2026-06-20T19:00:00-04:00',
  asset: {
    id: 'DEMO-BESS-03',
    label: 'Synthetic BESS 03',
    kind: 'bess',
    capacityMw: 10,
    bessCapacityMwh: 24,
  },
  window: {
    start: '2026-06-20T17:00:00-04:00',
    end: '2026-06-20T19:00:00-04:00',
  },
  observations: [
    observation({
      id: 'bess-mismatch-ems-soc',
      kind: 'telemetry',
      observedAt: '2026-06-20T18:58:00-04:00',
      assetId: 'DEMO-BESS-03',
      signal: 'bess.ems_soc_pct',
      value: 72,
      unit: '%',
      quality: 'valid',
      source: source('DEMO-EMS-03', 'Synthetic BESS EMS'),
      statement: 'Synthetic EMS state of charge is 72%.',
    }),
    observation({
      id: 'bess-mismatch-meter-soc',
      kind: 'telemetry',
      observedAt: '2026-06-20T18:58:00-04:00',
      assetId: 'DEMO-BESS-03',
      signal: 'bess.meter_soc_pct',
      value: 60.5,
      unit: '%',
      quality: 'valid',
      source: source('DEMO-BESS-METER-03', 'Synthetic independent BESS meter'),
      statement: 'Synthetic meter-derived state of charge is 60.5%.',
    }),
    observation({
      id: 'bess-mismatch-ems-power',
      kind: 'telemetry',
      observedAt: '2026-06-20T18:58:00-04:00',
      assetId: 'DEMO-BESS-03',
      signal: 'bess.ems_power_mw',
      value: 3.2,
      unit: 'MW',
      quality: 'valid',
      source: source('DEMO-EMS-03', 'Synthetic BESS EMS'),
      statement: 'Synthetic EMS discharge power is 3.2 MW.',
    }),
    observation({
      id: 'bess-mismatch-meter-power',
      kind: 'telemetry',
      observedAt: '2026-06-20T18:58:00-04:00',
      assetId: 'DEMO-BESS-03',
      signal: 'bess.meter_power_mw',
      value: 1.9,
      unit: 'MW',
      quality: 'valid',
      source: source('DEMO-BESS-METER-03', 'Synthetic independent BESS meter'),
      statement: 'Synthetic independent meter discharge power is 1.9 MW.',
    }),
    observation({
      id: 'bess-mismatch-temperature',
      kind: 'telemetry',
      observedAt: '2026-06-20T18:58:00-04:00',
      assetId: 'DEMO-BESS-03',
      signal: 'bess.temperature_c',
      value: 29,
      unit: 'C',
      quality: 'valid',
      source: source('DEMO-BMS-03', 'Synthetic BMS read-only feed'),
      statement: 'Synthetic maximum reported enclosure temperature is 29 C.',
    }),
    observation({
      id: 'bess-mismatch-bms-alarm-clear',
      kind: 'alarm',
      observedAt: '2026-06-20T18:58:00-04:00',
      assetId: 'DEMO-BESS-03',
      signal: 'bess.alarm_code',
      value: 'NONE',
      unit: 'state',
      quality: 'valid',
      source: source('DEMO-BMS-03', 'Synthetic BMS read-only feed'),
      statement: 'No active thermal or cell alarm appears in the synthetic BMS alarm list.',
    }),
    observation({
      id: 'bess-mismatch-calibration-gap',
      kind: 'data-quality',
      observedAt: '2026-06-20T19:00:00-04:00',
      assetId: 'DEMO-BESS-METER-03',
      signal: 'meter.calibration_verified',
      value: null,
      unit: 'boolean',
      quality: 'missing',
      source: source('DEMO-BESS-METER-03', 'Synthetic independent BESS meter'),
      statement: 'Meter calibration verification is not included in the synthetic sample.',
    }),
  ],
};

const hybridCommunicationLoss: IncidentScenario = {
  schemaVersion: '1.0',
  id: 'synthetic-hybrid-communication-loss',
  title: 'Hybrid communication loss and stale data',
  description:
    'Synthetic gateway outage with stale PV and BESS telemetry and no independent current power measurement.',
  synthetic: true,
  analysisAsOf: '2026-06-21T10:30:00-04:00',
  asset: {
    id: 'DEMO-HYBRID-04',
    label: 'Synthetic Hybrid Site 04',
    kind: 'hybrid',
    capacityMw: 36,
    bessCapacityMwh: 16,
  },
  window: {
    start: '2026-06-21T09:00:00-04:00',
    end: '2026-06-21T10:30:00-04:00',
  },
  observations: [
    observation({
      id: 'hybrid-comm-gateway-offline',
      kind: 'alarm',
      observedAt: '2026-06-21T09:02:00-04:00',
      assetId: 'DEMO-GATEWAY-04',
      signal: 'communications.status',
      value: 'OFFLINE',
      unit: 'state',
      quality: 'valid',
      source: source('DEMO-NETWORK-MONITOR-04', 'Synthetic network monitor'),
      statement: 'The synthetic network monitor reports the site gateway offline.',
    }),
    observation({
      id: 'hybrid-comm-data-age',
      kind: 'data-quality',
      observedAt: '2026-06-21T10:30:00-04:00',
      assetId: 'DEMO-GATEWAY-04',
      signal: 'data.age_minutes',
      value: 95,
      unit: 'minutes',
      quality: 'valid',
      source: source('DEMO-NETWORK-MONITOR-04', 'Synthetic network monitor'),
      statement: 'The latest synthetic operational packet is 95 minutes old.',
    }),
    observation({
      id: 'hybrid-comm-last-pv-power',
      kind: 'telemetry',
      observedAt: '2026-06-21T08:55:00-04:00',
      assetId: 'DEMO-HYBRID-04',
      signal: 'pv.actual_power_mw',
      value: 18,
      unit: 'MW',
      quality: 'stale',
      source: source('DEMO-GATEWAY-04', 'Synthetic site gateway'),
      statement: 'Last available synthetic PV power was 18 MW before telemetry became stale.',
    }),
    observation({
      id: 'hybrid-comm-expected-pv-power',
      kind: 'weather',
      observedAt: '2026-06-21T10:25:00-04:00',
      assetId: 'DEMO-HYBRID-04',
      signal: 'pv.expected_power_mw',
      value: 29,
      unit: 'MW',
      quality: 'suspect',
      source: source('DEMO-MODEL-04', 'Synthetic expected-power model'),
      statement: 'Synthetic model expectation is 29 MW, but current site telemetry is unavailable.',
    }),
    observation({
      id: 'hybrid-comm-last-bess-soc',
      kind: 'telemetry',
      observedAt: '2026-06-21T08:55:00-04:00',
      assetId: 'DEMO-BESS-04',
      signal: 'bess.ems_soc_pct',
      value: 54,
      unit: '%',
      quality: 'stale',
      source: source('DEMO-GATEWAY-04', 'Synthetic site gateway'),
      statement: 'Last available synthetic BESS state of charge was 54% before telemetry became stale.',
    }),
    observation({
      id: 'hybrid-comm-poi-meter-gap',
      kind: 'data-quality',
      observedAt: '2026-06-21T10:30:00-04:00',
      assetId: 'DEMO-POI-METER-04',
      signal: 'grid.poi_power_mw',
      value: null,
      unit: 'MW',
      quality: 'missing',
      source: source('DEMO-POI-METER-04', 'Synthetic independent POI meter'),
      statement: 'No current independent POI power reading is included in the synthetic scenario.',
    }),
  ],
};

export const SYNTHETIC_INCIDENT_SCENARIOS = [
  pvInverterBlockDerating,
  ambiguousPvUnderperformance,
  bessEmsMeterMismatch,
  hybridCommunicationLoss,
] as const satisfies readonly IncidentScenario[];

export type SyntheticIncidentScenarioId =
  (typeof SYNTHETIC_INCIDENT_SCENARIOS)[number]['id'];

export const getSyntheticScenario = (id: string): IncidentScenario => {
  const scenario = SYNTHETIC_INCIDENT_SCENARIOS.find((item) => item.id === id);
  if (!scenario) {
    throw new Error(`Unknown synthetic incident scenario: ${id}`);
  }
  return scenario;
};
