export const PV_METRICS_VERSION_REGISTRY = {
  appName: 'ORBI PVMetrics IA',
  internalVersion: '0.1O-Z.4A-independent-demo-preservation-final-roadmap-freeze-final-qa-closure',
  currentStableModule:
    '1O-Z.4A — Independent Demo Preservation & Final Roadmap Freeze Final QA & Closure',
  currentRoadmapBlock:
    '1O-Z — Independent Demo Preservation & Final Roadmap Freeze',
  nextRecommendedModule:
    'POST-1O-Z — Optional Future Roadmap Only Under New Explicit Scope',
  buildContext: 'Google IA Studio standalone isolated build',
  safetyMode:
    'Standalone Safe Mode + Sovereign Safe Mode + SCADA Read-Only First',
  maturityLabel:
    'Pre-pilot read-only preparation. No real SCADA connection enabled.',
  contextLock:
    'PVMetrics-only context. Photovoltaic performance, BESS, source-of-truth, validation, evidence and read-only scope.',
  lastKnownStableFlow: [
    '1O-D.1 — Client Validation & Source-of-Truth Gate',
    '1O-D.2 — Client Validation Request Pack',
    '1O-D.3 — Client Evidence Response Simulator',
    '1O-D.4A — Client Validation Decision Engine Base',
    '1O-D.4B — Client Validation Decision Visual Layer & Export',
    '1O-E.1A — Read-Only Pilot Scope Engine Base',
    '1O-E.1B — Read-Only Pilot Scope Visual Layer & Wizard Integration',
    '1O-E.2 — PVMetrics Internal Version Registry & Module Traceability Badge',
    '1O-E.3A — Read-Only Pilot Signal Checklist & Client Review Pack Base',
    '1O-E.3B — Read-Only Pilot Review Pack Visual Layer & Export',
    '1O-E.4A — Read-Only Pilot Go/No-Go Checklist Base',
    '1O-E.4B — Read-Only Pilot Go/No-Go Visual Layer & Export',
    '1O-E.5A — Read-Only Pilot Data Contract Draft Base',
    '1O-E.5B — Read-Only Pilot Data Contract Visual Layer & Export',
    '1O-E.6A — Read-Only Pilot Final Handoff Package Base',
    '1O-E.6B — Read-Only Pilot Final Handoff Visual Layer & Export',
    '1O-F.1A.1 — Connector Blueprint Types & Safety Taxonomy',
    '1O-F.0 — Suncast Competitive Gap Register & Forecast Strategy Lock',
    '1O-F.1A — Solar Forecasting Product Types & Blueprint Base',
    '1O-F.1B.1 — Solar Forecast Mock Series Engine Base',
    '1O-F.1B.2 — Solar Forecast Explanation, Risk & KPI Summary Engine',
    '1O-F.1C.1 — Solar Forecast Visual Card & Curve Table',
    '1O-F.1C.2 — Solar Forecast Export Box & Wizard Integration',
    '1O-F.2A — CEN Forecast Compliance Simulator Types & Regulatory Blueprint',
    '1O-F.2B — CEN Forecast Compliance Mock Engine',
    '1O-F.2C.1 — CEN Compliance Visual Card',
    '1O-F.2C.2 — CEN Compliance Export Box & Wizard Integration',
    '1O-F.3A — Availability / Outage / Limitation Event Types & Blueprint',
    '1O-F.3B — Availability / Outage / Limitation Mock Event Engine',
    '1O-F.3C.1 — Operational Events Visual Card',
    '1O-F.3C.2 — Operational Events Export Box & Wizard Integration',
    '1O-F.4A — Forecast Accuracy & Error Analytics Types & Blueprint',
    '1O-F.4B — Forecast Accuracy & Error Analytics Mock Engine',
    '1O-F.4C.1 — Forecast Accuracy Visual Card',
    '1O-F.4C.2 — Forecast Accuracy Export Box & Wizard Integration',
    '1O-F.5A.1 — Soiling & Cleaning Types Base',
    '1O-F.5A.2 — Soiling & Cleaning Blueprint Data',
    '1O-F.5B.1 — Soiling & Cleaning Mock Types',
    '1O-F.5B.2 — Soiling & Cleaning Mock Engine',
    '1O-F.5C.1 — Soiling & Cleaning Visual Card',
    '1O-F.5C.2 — Soiling & Cleaning Export Box & Wizard Integration',
    '1O-F.6A — Commercial Impact & Revenue Risk Types',
    '1O-F.6B — Commercial Impact & Revenue Risk Blueprint Data',
    '1O-F.6C.1 — Commercial Impact & Revenue Risk Mock Types',
    '1O-F.6C.2 — Commercial Impact & Revenue Risk Mock Engine',
    '1O-F.6D.1 — Commercial Impact Visual Card',
    '1O-F.6D.2 — Commercial Impact Export Box & Wizard Integration',
    '1O-F.7A — Executive Forecast Intelligence Summary Types',
    '1O-F.7B — Executive Forecast Intelligence Summary Mock Engine',
    '1O-F.7C.1 — Executive Forecast Intelligence Visual Card',
    '1O-F.7C.2 — Executive Forecast Intelligence Export Box & Wizard Integration',
    '1O-F.8A — Competitive Forecast Strategy Final QA & Closure',
    '1O-G.0 — Read-Only Data Contract & Connector Readiness Blueprint',
    '1O-G.1A — Read-Only Data Contract Types',
    '1O-G.1B — Read-Only Data Contract Mock Validator',
    '1O-G.2A — Source Freshness & Data Quality Gate Types',
    '1O-G.2B — Source Freshness & Data Quality Gate Mock Engine',
    '1O-G.2C.1 — Source Freshness & Data Quality Gate Visual Card',
    '1O-G.2C.2 — Source Freshness & Data Quality Gate Export Box & Wizard Integration',
    '1O-G.3A — Future Connector Registry Types',
    '1O-G.3B — Future Connector Registry Mock Data',
    '1O-G.3C.1 — Future Connector Registry Visual Card',
    '1O-G.3C.2 — Future Connector Registry Export Box & Wizard Integration',
    '1O-G.4A — Read-Only Connector Readiness Final QA & Closure',
    '1O-H.0 — Controlled Read-Only Integration Sandbox Blueprint',
    '1O-H.1A — Controlled Sandbox Types',
    '1O-H.1B.1 — Controlled Sandbox Mock Session Base Engine',
    '1O-H.1B.2 — Controlled Sandbox Run Result & Registry Engine',
    '1O-H.2A — Sandbox Gate Replay Mock Data',
    '1O-H.2B — Sandbox Gate Replay Visual Card',
    '1O-H.2C.1 — Sandbox Gate Replay Export Box',
    '1O-H.2C.2 — Sandbox Gate Replay Wizard Integration',
    '1O-H.3A — Controlled Sandbox Final QA & Closure',
    '1O-I.0 — Pilot Evidence Pack & Client Demo Blueprint',
    '1O-I.1A — Pilot Evidence Pack Types',
    '1O-I.1B — Pilot Evidence Pack Mock Data',
    '1O-I.2A — Client Demo Narrative Card',
    '1O-I.2B — Pilot Evidence Export Text Box',
    '1O-I.3A — Pilot Evidence Pack Wizard Integration',
    '1O-I.4A — Pilot Evidence Final QA & Closure',
    '1O-J.0 — Local Demo Mode Hardening & Presentation Flow Blueprint',
    '1O-J.1A — Local Demo Mode Types',
    '1O-J.1B — Local Demo Mode Mock State',
    '1O-J.2A — Presentation Flow Visual Card',
    '1O-J.2B — Demo Safety Locks Visual Card',
    '1O-J.3A — Local Demo Mode Wizard Integration',
    '1O-J.4A — Local Demo Mode Final QA & Closure',
    '1O-K.0 — Client Pilot Handoff & Safe Next Steps Blueprint',
    '1O-K.1A — Client Pilot Handoff Types',
    '1O-K.1B — Client Pilot Handoff Mock Data',
    '1O-K.2A — Client Pilot Handoff Visual Card',
    '1O-K.2B — Safe Next Steps Export Text Box',
    '1O-K.3A — Client Pilot Handoff Wizard Integration',
    '1O-K.4A — Client Pilot Handoff Final QA & Closure',
    '1O-L.0 — Standalone Client Demo Release Candidate Blueprint',
    '1O-L.1A — Release Candidate Types',
    '1O-L.1B — Release Candidate Mock Data',
    '1O-L.2A — Release Candidate Readiness Visual Card',
    '1O-L.2B — Release Candidate Checklist Export Text Box',
    '1O-L.3A — Release Candidate Wizard Integration',
    '1O-L.4A — Release Candidate Final QA & Closure',
    '1O-M.0 — Local Demo Package Assembly & Operator Sign-Off Blueprint',
    '1O-M.1A — Local Demo Package Types',
    '1O-M.1B — Local Demo Package Mock Data',
    '1O-M.2A — Operator Sign-Off Visual Card',
    '1O-M.2B — Local Demo Package Assembly Export Text Box',
    '1O-M.3A — Local Demo Package Wizard Integration',
    '1O-M.4A — Local Demo Package Final QA & Closure',
    '1O-N.0 — Controlled Client Demo Session Runbook Blueprint',
    '1O-N.1A — Controlled Demo Session Types',
    '1O-N.1B.1 — Controlled Demo Session Mock Data Base',
    '1O-N.1B.2 — Controlled Demo Session Mock Data Completion',
    '1O-N.2A — Demo Session Runbook Visual Card',
    '1O-N.2B — Demo Session Script Export Text Box',
    '1O-N.3A — Demo Session Wizard Integration',
    '1O-N.4A — Demo Session Final QA & Closure',
    '1O-O.0 — Controlled Client Demo Feedback & Pilot Readiness Blueprint',
    '1O-O.1A — Client Demo Feedback Types',
    '1O-O.1B — Client Demo Feedback Mock Data',
    '1O-O.2A — Feedback & Pilot Readiness Visual Card',
    '1O-O.2B — Feedback Summary Export Text Box',
    '1O-O.3A — Feedback & Pilot Readiness Wizard Integration',
    '1O-O.4A — Feedback & Pilot Readiness Final QA & Closure',
    '1O-P.0 — Controlled Pilot Scope & Read-Only Integration Agreement Blueprint',
    '1O-P.1A — Controlled Pilot Scope Types',
    '1O-P.1B — Controlled Pilot Scope Mock Data',
    '1O-P.2A — Pilot Scope & Read-Only Agreement Visual Card',
    '1O-P.2B — Pilot Agreement Export Text Box',
    '1O-P.3A — Pilot Scope Wizard Integration',
    '1O-P.4A — Pilot Scope Final QA & Closure',
    '1O-Q.0 — Controlled Read-Only Connector Readiness Blueprint',
    '1O-Q.1A — Read-Only Connector Readiness Types',
    '1O-Q.1B — Read-Only Connector Readiness Mock Data',
    '1O-Q.2A — Connector Readiness Visual Card',
    '1O-Q.2B — Connector Readiness Export Text Box',
    '1O-Q.3A — Connector Readiness Wizard Integration',
    '1O-Q.4A — Connector Readiness Final QA & Closure',
    '1O-R.0 — Controlled Read-Only Data Contract Blueprint',
    '1O-R.1A — Read-Only Data Contract Types',
    '1O-R.1B — Read-Only Data Contract Mock Data',
    '1O-R.2A — Data Contract Visual Card',
    '1O-R.2B — Data Contract Export Text Box',
    '1O-R.3A — Data Contract Wizard Integration',
    '1O-R.4A — Data Contract Final QA & Closure',
    '1O-S.0 — Controlled Sanitized Sample Data Blueprint',
    '1O-S.1A — Sanitized Sample Data Types',
    '1O-S.1B — Sanitized Sample Data Mock Data',
    '1O-S.2A — Sanitized Sample Data Visual Card',
    '1O-S.2B — Sanitized Sample Data Export Text Box',
    '1O-S.3A — Sanitized Sample Data Wizard Integration',
    '1O-S.4A — Sanitized Sample Data Final QA & Closure',
    '1O-T.0 — Controlled Client Demo Evidence Freeze Blueprint',
    '1O-T.1A — Client Demo Evidence Freeze Types',
    '1O-T.1B — Client Demo Evidence Freeze Mock Data',
    '1O-T.2A — Client Demo Evidence Freeze Visual Card',
    '1O-T.2B — Client Demo Evidence Export Text Box',
    '1O-T.3A — Client Demo Evidence Wizard Integration',
    '1O-T.4A — Client Demo Evidence Final QA & Closure',
    '1O-U.0 — Controlled Client Demo Delivery Readiness Blueprint',
    '1O-U.1A — Client Demo Delivery Readiness Types',
    '1O-U.1B — Client Demo Delivery Readiness Mock Data',
    '1O-U.2A — Client Demo Delivery Readiness Visual Card',
    '1O-U.2B — Client Demo Delivery Export Text Box',
    '1O-U.3A — Client Demo Delivery Wizard Integration',
    '1O-U.4A — Client Demo Delivery Final QA & Closure',
    '1O-V.0 — Controlled Client Demo Presentation Script Blueprint',
    '1O-V.1A — Client Demo Presentation Script Types',
    '1O-V.1B — Client Demo Presentation Script Mock Data',
    '1O-V.2A — Client Demo Presentation Script Visual Card',
    '1O-V.2B — Client Demo Presentation Script Export Text Box',
    '1O-V.3A — Client Demo Presentation Script Wizard Integration',
    '1O-V.4A — Client Demo Presentation Script Final QA & Closure',
    '1O-W.0 — Controlled Client Demo Final Review Board Blueprint',
    '1O-W.1A — Client Demo Final Review Board Types',
    '1O-W.1B — Client Demo Final Review Board Mock Data',
    '1O-W.2A — Client Demo Final Review Board Visual Card',
    '1O-W.2B — Client Demo Final Review Board Export Text Box',
    '1O-W.3A — Client Demo Final Review Board Wizard Integration',
    '1O-W.4A — Client Demo Final Review Board Final QA & Closure',
    '1O-X.0 — Controlled Client Demo Master Closure Blueprint',
    '1O-X.1A — Client Demo Master Closure Types',
    '1O-X.1B — Client Demo Master Closure Mock Data',
    '1O-X.2A — Client Demo Master Closure Visual Card',
    '1O-X.2B — Client Demo Master Closure Export Text Box',
    '1O-X.3A — Client Demo Master Closure Wizard Integration',
    '1O-X.4A — Client Demo Master Closure Final QA & Closure',
    '1O-Y.0 — Controlled Client Demo Archive & Read-Only Maintenance Blueprint',
    '1O-Y.1A — Client Demo Archive & Read-Only Maintenance Types',
    '1O-Y.1B — Client Demo Archive & Read-Only Maintenance Mock Data',
    '1O-Y.2A — Client Demo Archive & Read-Only Maintenance Visual Card',
    '1O-Y.2B — Client Demo Archive & Read-Only Maintenance Export Text Box',
    '1O-Y.3A — Client Demo Archive & Read-Only Maintenance Wizard Integration',
    '1O-Y.4A — Client Demo Archive & Read-Only Maintenance Final QA & Closure',
    '1O-Z.0 — Independent Demo Preservation & Final Roadmap Freeze Blueprint',
    '1O-Z.1A — Independent Demo Preservation & Final Roadmap Freeze Types',
    '1O-Z.1B — Independent Demo Preservation & Final Roadmap Freeze Mock Data',
    '1O-Z.2A — Independent Demo Preservation & Final Roadmap Freeze Visual Card',
    '1O-Z.2B — Independent Demo Preservation & Final Roadmap Freeze Export Text Box',
    '1O-Z.3A — Independent Demo Preservation & Final Roadmap Freeze Wizard Integration',
    '1O-Z.4A — Independent Demo Preservation & Final Roadmap Freeze Final QA & Closure',
  ],
  safetyBoundaries: [
    'No SCADA real.',
    'No APIs reales.',
    'No lectura de medidores reales.',
    'No backend productivo.',
    'No localStorage para versionado.',
    'No telecontrol.',
    'No modificación de setpoints.',
    'No comandos a BESS.',
    'No comandos a inversores.',
    'No credenciales productivas en frontend.',
  ],
} as const;

export type PVMetricsVersionRegistry = typeof PV_METRICS_VERSION_REGISTRY;
