import React, { useMemo, useState } from 'react';
import { FileText, Link2, Search, ShieldCheck } from 'lucide-react';
import type { CommissioningWorkspaceState } from '../application/commissioningService';
import type { CommissioningAsset, Evidence, EvidenceType, TestExecution } from '../contracts';
import { useCommissioningI18n } from '../localization/CommissioningLocaleContext';

type TypeFilter = 'ALL' | EvidenceType;
const evidenceTypes: EvidenceType[] = ['PHOTO','SCREENSHOT','CSV','XLSX','LOG','GRAPH','MEASUREMENT','PDF','DOCUMENT','SCADA','BMS','PCS','COMMENT'];
const typeClass: Record<EvidenceType, string> = {
  PHOTO:'border-violet-500/25 bg-violet-500/10 text-violet-300', SCREENSHOT:'border-violet-500/25 bg-violet-500/10 text-violet-300', CSV:'border-cyan-500/25 bg-cyan-500/10 text-cyan-300', XLSX:'border-cyan-500/25 bg-cyan-500/10 text-cyan-300', LOG:'border-slate-500/25 bg-slate-500/10 text-slate-300', GRAPH:'border-blue-500/25 bg-blue-500/10 text-blue-300', MEASUREMENT:'border-emerald-500/25 bg-emerald-500/10 text-emerald-300', PDF:'border-rose-500/25 bg-rose-500/10 text-rose-300', DOCUMENT:'border-gray-500/25 bg-gray-500/10 text-gray-300', SCADA:'border-amber-500/25 bg-amber-500/10 text-amber-300', BMS:'border-amber-500/25 bg-amber-500/10 text-amber-300', PCS:'border-orange-500/25 bg-orange-500/10 text-orange-300', COMMENT:'border-gray-500/25 bg-gray-500/10 text-gray-300',
};
const shortHash = (value:string):string => value.length>20?`${value.slice(0,12)}…${value.slice(-8)}`:value;

export const CommissioningEvidenceView: React.FC<{ state: CommissioningWorkspaceState }> = ({ state }) => {
  const i18n=useCommissioningI18n(); const t=i18n.text; const snapshot=state.snapshot; const evidence=snapshot.evidence;
  const [typeFilter,setTypeFilter]=useState<TypeFilter>('ALL'); const [query,setQuery]=useState('');
  const assetById=useMemo(()=>new Map<string,CommissioningAsset>(snapshot.assets.map((asset):[string,CommissioningAsset]=>[asset.assetId,asset])),[snapshot.assets]);
  const executionById=useMemo(()=>new Map<string,TestExecution>(snapshot.testExecutions.map((execution):[string,TestExecution]=>[execution.executionId,execution])),[snapshot.testExecutions]);
  const linksByEvidenceId=useMemo(()=>{const links=new Map<string,string[]>(); const add=(id:string,es:string,en:string)=>{const current=links.get(id)??[]; current.push(t(es,en)); links.set(id,current);}; snapshot.anomalies.forEach((item)=>item.evidenceIds.forEach((id)=>add(id,`Anomalía · ${item.anomalyId}`,`Anomaly · ${item.anomalyId}`))); snapshot.findings.forEach((item)=>item.evidenceIds.forEach((id)=>add(id,`Hallazgo · ${item.findingId}`,`Finding · ${item.findingId}`))); snapshot.punchItems.forEach((item)=>item.closureEvidenceIds.forEach((id)=>add(id,`Cierre de Pendiente · ${item.punchItemId}`,`Punch closure · ${item.punchItemId}`))); snapshot.criterionEvaluations.forEach((item)=>item.evidenceIds.forEach((id)=>add(id,`Evaluación de criterio · ${item.criterionEvaluationId}`,`Criterion evaluation · ${item.criterionEvaluationId}`))); snapshot.testPhases.forEach((item)=>item.evidenceIds.forEach((id)=>add(id,`Fase de prueba · ${item.testPhaseId}`,`Test phase · ${item.testPhaseId}`))); snapshot.events.forEach((item)=>item.evidenceIds.forEach((id)=>add(id,`Evento · ${item.eventId}`,`Event · ${item.eventId}`))); snapshot.gates.forEach((item)=>item.evidenceIds.forEach((id)=>add(id,`Hito · ${item.gateId}`,`Gate · ${item.gateId}`))); snapshot.handoverPackages.forEach((item)=>item.evidenceIds.forEach((id)=>add(id,`Entrega · ${item.handoverPackageId}`,`Handover · ${item.handoverPackageId}`))); snapshot.datasets.forEach((item)=>{if(item.rawEvidenceId)add(item.rawEvidenceId,`Dataset · ${item.datasetId}`,`Dataset · ${item.datasetId}`)}); return links;},[snapshot,t]);
  const filtered=useMemo(()=>{const normalized=query.trim().toLowerCase(); return evidence.filter((item)=>{if(typeFilter!=='ALL'&&item.type!==typeFilter)return false;if(!normalized)return true;const asset=item.assetId?assetById.get(item.assetId):undefined;const linked=linksByEvidenceId.get(item.evidenceId)??[];return [item.evidenceId,item.name,item.source,item.description,item.fileReference,item.sha256,asset?.name,...linked].filter(Boolean).some((value)=>String(value).toLowerCase().includes(normalized));});},[assetById,evidence,linksByEvidenceId,query,typeFilter]);

  if(evidence.length===0)return <div className="space-y-5" id="commissioning-evidence-view"><div><p className="text-[10px] font-black uppercase tracking-wider text-gray-500">{t('Evidencias','Evidence')}</p><h2 className="mt-1 text-lg font-bold text-white">{t('No hay registros de evidencia cargados','No evidence records loaded')}</h2></div><div className="rounded-xl border border-dashed border-gray-700 bg-gray-950 p-8 text-center"><FileText className="mx-auto h-8 w-8 text-gray-600"/><p className="mt-3 text-sm font-semibold text-gray-200">{t('El snapshot actual no contiene evidencias de Puesta en Servicio registradas.','The current snapshot contains no registered commissioning evidence.')}</p><p className="mx-auto mt-2 max-w-2xl text-xs leading-relaxed text-gray-500">{t('La evidencia puede provenir de importación de archivos aprobados, registro manual o datos PVMetrics existentes de solo lectura. La evidencia faltante debe permanecer faltante; esta interfaz nunca inventa archivos, mediciones, capturas ni hashes.','Evidence may originate from approved file import, manual registration or existing read-only PVMetrics data. Missing evidence must remain missing; this UI never invents a file, measurement, screenshot or hash.')}</p></div></div>;

  const withHash=evidence.filter((item)=>Boolean(item.sha256)).length; const executionLinked=evidence.filter((item)=>Boolean(item.executionId)).length; const assetScoped=evidence.filter((item)=>Boolean(item.assetId)).length; const referenced=evidence.filter((item)=>(linksByEvidenceId.get(item.evidenceId)?.length??0)>0).length;
  return <div className="space-y-5" id="commissioning-evidence-view">
    <div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-black uppercase tracking-wider text-gray-500">{t('Evidencias','Evidence')}</p><h2 className="mt-1 text-lg font-bold text-white">{t('Repositorio de evidencias de Puesta en Servicio','Commissioning evidence vault')}</h2><p className="mt-1 text-xs text-gray-500">{t('Registro de evidencias de solo lectura con fuente, vínculo a activo/ejecución y trazabilidad posterior explícitos.','Read-only evidence registry with explicit source, asset/execution linkage and downstream traceability.')}</p></div><div className="rounded-lg border border-cyan-500/15 bg-cyan-500/5 px-3 py-2 text-[10px] font-semibold text-cyan-200">{t('HASH REGISTRADO ≠ HASH VERIFICADO · SIN FABRICACIÓN DE EVIDENCIA','HASH RECORDED ≠ HASH VERIFIED · NO EVIDENCE FABRICATION')}</div></div>
    <section className="grid grid-cols-2 gap-3 md:grid-cols-5" aria-label={t('Resumen de evidencias','Evidence summary')}>{[[t('Total','Total'),evidence.length],[t('SHA-256 registrado','SHA-256 recorded'),withHash],[t('Vinculada a ejecución','Execution-linked'),executionLinked],[t('Asociada a activo','Asset-scoped'),assetScoped],[t('Referenciada posteriormente','Referenced downstream'),referenced]].map(([label,value])=><article key={String(label)} className="rounded-xl border border-gray-800 bg-gray-950 p-4"><p className="text-[9px] font-black uppercase text-gray-500">{label}</p><p className="mt-2 text-2xl font-black text-white">{value}</p></article>)}</section>
    <section className="grid grid-cols-1 gap-3 lg:grid-cols-[1fr_auto]" aria-label={t('Filtros de evidencias','Evidence filters')}><label className="relative block"><span className="sr-only">{t('Buscar evidencias','Search evidence')}</span><Search className="pointer-events-none absolute left-3 top-3.5 h-4 w-4 text-gray-600"/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder={t('Buscar ID, nombre, fuente, activo, archivo o vínculo de trazabilidad','Search ID, name, source, asset, file or traceability link')} className="min-h-11 w-full rounded-lg border border-gray-800 bg-gray-950 pl-10 pr-3 text-xs text-gray-200 outline-none placeholder:text-gray-700 focus:border-emerald-500"/></label><label className="text-[9px] font-bold uppercase tracking-wider text-gray-500">{t('Tipo','Type')}<select value={typeFilter} onChange={(event)=>setTypeFilter(event.target.value as TypeFilter)} className="ml-2 min-h-11 rounded-lg border border-gray-800 bg-gray-950 px-3 text-xs font-semibold normal-case tracking-normal text-gray-200"><option value="ALL">{t('Todas las evidencias','All evidence')}</option>{evidenceTypes.map((type)=><option key={type} value={type}>{type}</option>)}</select></label></section>
    {filtered.length===0?<div className="rounded-xl border border-dashed border-gray-700 bg-gray-950 p-8 text-center text-xs text-gray-500">{t('Ningún registro de evidencia coincide con los filtros actuales.','No evidence records match the current filters.')}</div>:<div className="space-y-3">{filtered.map((item:Evidence)=>{const asset=item.assetId?assetById.get(item.assetId):undefined; const execution=item.executionId?executionById.get(item.executionId):undefined; const links=linksByEvidenceId.get(item.evidenceId)??[]; return <article key={item.evidenceId} className="rounded-xl border border-gray-800 bg-gray-950 p-5"><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div className="flex min-w-0 items-start gap-3"><FileText className="mt-0.5 h-5 w-5 shrink-0 text-cyan-400"/><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={`rounded border px-2 py-1 text-[9px] font-black ${typeClass[item.type]}`}>{item.type}</span><span className="rounded border border-gray-700 bg-gray-900 px-2 py-1 text-[9px] font-bold text-gray-300">{t('FUENTE','SOURCE')} · {item.source}</span></div><h3 className="mt-3 text-sm font-bold text-white">{item.name}</h3><p className="mt-2 max-w-4xl text-xs leading-relaxed text-gray-400">{item.description??t('No hay descripción adicional de evidencia registrada.','No additional evidence description recorded.')}</p></div></div><p className="shrink-0 font-mono text-[9px] text-gray-600">{item.evidenceId}</p></div>
      <div className="mt-4 grid grid-cols-2 gap-2 md:grid-cols-4 xl:grid-cols-7 text-[10px]"><div className="rounded-lg border border-gray-800 bg-gray-900 p-3"><p className="text-gray-600">{t('Activo','Asset')}</p><p className="mt-1 font-semibold text-gray-300">{asset?.name??item.assetId??t('PROYECTO / GENERAL','PROJECT / GENERAL')}</p></div><div className="rounded-lg border border-gray-800 bg-gray-900 p-3"><p className="text-gray-600">{t('Ejecución','Execution')}</p><p className="mt-1 break-all font-mono text-gray-400">{execution?.executionId??item.executionId??t('NO VINCULADA','NOT LINKED')}</p></div><div className="rounded-lg border border-gray-800 bg-gray-900 p-3"><p className="text-gray-600">{t('Capturada el','Captured at')}</p><p className="mt-1 font-semibold text-gray-300">{item.capturedAt??i18n.notRecorded}</p></div><div className="rounded-lg border border-gray-800 bg-gray-900 p-3"><p className="text-gray-600">{t('Referencia de archivo','File reference')}</p><p className="mt-1 break-all font-mono text-gray-400">{item.fileReference??i18n.notRecorded}</p></div><div className={`rounded-lg border p-3 ${item.sha256?'border-emerald-500/15 bg-emerald-500/5':'border-gray-800 bg-gray-900'}`}><p className="text-gray-600">SHA-256</p><p className={`mt-1 font-mono ${item.sha256?'text-emerald-300':'text-gray-500'}`}>{item.sha256?shortHash(item.sha256):i18n.notRecorded}</p></div><div className="rounded-lg border border-violet-500/15 bg-violet-500/5 p-3"><p className="text-violet-300">{t('Vínculos de trazabilidad','Trace links')}</p><p className="mt-1 text-lg font-bold text-white">{links.length}</p></div><div className="rounded-lg border border-gray-800 bg-gray-900 p-3"><p className="text-gray-600">{t('Creada por','Created by')}</p><p className="mt-1 font-semibold text-gray-300">{item.createdBy}</p></div></div>
      <div className="mt-4 rounded-lg border border-gray-800 bg-gray-900 p-3"><div className="flex items-center gap-2"><Link2 className="h-3.5 w-3.5 text-cyan-400"/><p className="text-[9px] font-black uppercase tracking-wider text-gray-600">{t('Trazabilidad posterior','Downstream traceability')}</p></div>{links.length===0?<p className="mt-2 text-[10px] text-gray-500">{t('Ningún consumidor posterior referencia actualmente este ID de evidencia.','No downstream consumer currently references this Evidence ID.')}</p>:<div className="mt-2 flex flex-wrap gap-2">{links.map((link)=><span key={link} className="rounded border border-gray-800 bg-gray-950 px-2 py-1 text-[10px] text-gray-400">{link}</span>)}</div>}</div></article>})}</div>}
    <div className="rounded-lg border border-gray-800 bg-gray-950 px-3 py-2 text-[10px] leading-relaxed text-gray-500"><ShieldCheck className="mr-1 inline h-3.5 w-3.5 text-emerald-400"/>{t('Un valor SHA-256 registrado se presenta solo como metadato. PVMetrics no debe etiquetar una evidencia como verificada criptográficamente salvo que un flujo explícito de verificación registre ese resultado.','A recorded SHA-256 value is presented as metadata only. PVMetrics must not label evidence as cryptographically verified unless an explicit verification workflow records that result.')}</div>
  </div>;
};