import React, { useMemo, useState } from 'react';
import { ClipboardCheck, Download, FileText, RefreshCw, ShieldCheck } from 'lucide-react';
import { CommissioningService, type CommissioningWorkspaceState } from '../application/commissioningService';
import { BrowserLocalStorageDriver, CommissioningRepository } from '../persistence';
import { buildCommissioningReport, type CommissioningReport } from '../reporting/commissioningReport';
import { renderLocalizedCommissioningReportText } from '../reporting/localizedCommissioningReport';
import { DEFAULT_COMMISSIONING_LOCALE, commissioningCanonicalLabel, commissioningText, type CommissioningLocale } from '../localization/commissioningLocale';

const downloadText=(content:string,filename:string,type:string)=>{const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=filename;anchor.click();URL.revokeObjectURL(url);};

export const CommissioningReportsPanel:React.FC<{locale?:CommissioningLocale}>=({locale=DEFAULT_COMMISSIONING_LOCALE})=>{
 const t=(es:string,en:string)=>commissioningText(locale,es,en); const canonical=(value:string)=>commissioningCanonicalLabel(locale,value);
 const service=useMemo(()=>new CommissioningService(new CommissioningRepository(new BrowserLocalStorageDriver(window.localStorage))),[]); const initialState=useMemo(()=>service.getState(),[service]);
 const [state,setState]=useState<CommissioningWorkspaceState>(initialState),[projectId,setProjectId]=useState(initialState.snapshot.projects[0]?.projectId??''),[scopeId,setScopeId]=useState(initialState.snapshot.scopes[0]?.scopeId??''),[report,setReport]=useState<CommissioningReport|null>(null),[message,setMessage]=useState('');
 const scopes=state.snapshot.scopes.filter(scope=>scope.projectId===projectId);
 const adoptState=(next:CommissioningWorkspaceState)=>{setState(next);const nextProjectId=next.snapshot.projects[0]?.projectId??'';const nextScopeId=next.snapshot.scopes.find(scope=>scope.projectId===nextProjectId)?.scopeId??'';setProjectId(nextProjectId);setScopeId(nextScopeId);setReport(null);setMessage('');};
 const refreshStored=()=>adoptState(service.getState()); const openSyntheticLab=()=>adoptState(service.initializeSyntheticLab()); const openSyntheticCertificationScenario=()=>adoptState(service.initializeSyntheticCertificationScenario());
 const handleProjectChange=(nextProjectId:string)=>{setProjectId(nextProjectId);setScopeId(state.snapshot.scopes.find(scope=>scope.projectId===nextProjectId)?.scopeId??'');setReport(null);setMessage('');};
 const generateReport=()=>{if(!projectId||!scopeId){setMessage(t('Selecciona un proyecto y un alcance de Puesta en Servicio antes de generar el informe.','Select a commissioning project and scope before generating the report.'));return;}try{const next=buildCommissioningReport({snapshot:state.snapshot,projectId,scopeId,generatedAt:new Date().toISOString(),generatedBy:'ORBI PVMetrics Report UI'});setReport(next);setMessage(t('Informe snapshot de Puesta en Servicio generado localmente. No se modificó ningún estado de Puesta en Servicio.','Commissioning snapshot report generated locally. No commissioning state was modified.'));}catch(error){setReport(null);setMessage(error instanceof Error?t('No fue posible generar el informe de Puesta en Servicio.','Unable to generate commissioning report.'):t('No fue posible generar el informe de Puesta en Servicio.','Unable to generate commissioning report.'));}};
 const exportJson=()=>{if(!report)return;downloadText(JSON.stringify(report,null,2),`ORBI_PVMetrics_Commissioning_${report.project.projectId}_${report.scope.revision}.json`,'application/json;charset=utf-8');};
 const exportText=()=>{if(!report)return;downloadText(renderLocalizedCommissioningReportText(report,locale),`ORBI_PVMetrics_Commissioning_${report.project.projectId}_${report.scope.revision}_${locale}.txt`,'text/plain;charset=utf-8');};
 const localizedLimitations=report&&locale==='es'?['Este informe se genera desde el snapshot almacenado de Puesta en Servicio y no emite comandos OT ni modifica sistemas de planta.','La evaluación analítica ORBI es distinta de la aceptación humana y de la aceptación contractual.','Los umbrales, documentos, evidencias o mapeos faltantes permanecen faltantes y no deben inferirse.','La trazabilidad conserva observaciones vinculadas a activos EXCLUIDOS registrados explícitamente; esto no incorpora esos activos al alcance de aceptación.','Un estado de entrega LISTO o APROBADO no autoriza energización ni operación.']:report?.limitations??[];

 if(state.loadStatus==='EMPTY'||state.snapshot.projects.length===0)return <section className="space-y-5" aria-label={t('Informes de Puesta en Servicio','Commissioning reports')}><div className="rounded-xl border border-emerald-500/20 bg-gray-900 p-5"><div className="flex items-start gap-3"><ClipboardCheck className="mt-0.5 h-5 w-5 text-emerald-400"/><div><p className="text-[10px] font-black uppercase tracking-wider text-emerald-300">{t('Informe de Puesta en Servicio BESS','BESS Commissioning Report')}</p><h2 className="mt-1 text-lg font-bold text-white">{t('No hay dataset de Puesta en Servicio almacenado','No stored commissioning dataset')}</h2><p className="mt-2 text-xs leading-relaxed text-gray-400">{t('Reportes lee el repositorio acotado de Puesta en Servicio. No hay un proyecto persistido disponible. Puede refrescar datos almacenados o abrir una vista sintética en memoria sin crear un registro real.','Reports reads the scoped Commissioning repository. No persisted project is currently available. You can refresh stored data or open a synthetic in-memory preview without creating a real commissioning record.')}</p></div></div></div><div className="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-[auto_1fr_1fr]"><button type="button" onClick={refreshStored} className="min-h-11 rounded-lg border border-gray-700 bg-gray-950 px-4 text-xs font-bold text-gray-300"><RefreshCw className="mr-2 inline h-3.5 w-3.5"/>{t('Refrescar datos almacenados','Refresh stored data')}</button><button type="button" onClick={openSyntheticLab} className="min-h-11 rounded-lg border border-emerald-500/30 bg-emerald-500/10 px-4 text-xs font-extrabold text-emerald-300">{t('Abrir vista sintética base','Open base synthetic preview')}</button><button type="button" onClick={openSyntheticCertificationScenario} className="min-h-11 rounded-lg bg-cyan-400 px-4 text-xs font-extrabold text-slate-950">{t('Abrir vista E2E procesada','Open processed E2E preview')}</button></div><div className="rounded-lg border border-amber-500/15 bg-amber-500/5 px-3 py-2 text-[10px] leading-relaxed text-amber-200">{t('Las vistas sintéticas existen solo en memoria. No crean un registro real de Puesta en Servicio, no autorizan energización, no conceden aceptación humana, no cierran Pendientes reales ni escriben en sistemas OT.','Synthetic previews are in-memory only. They do not create a real commissioning record, authorize energization, grant human acceptance, close real Punch Items or write to OT systems.')}</div></section>;

 return <section className="space-y-5" aria-label={t('Informes de Puesta en Servicio','Commissioning reports')}>
  <header className="rounded-xl border border-emerald-500/20 bg-gray-900 p-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-start gap-3"><FileText className="mt-0.5 h-5 w-5 text-emerald-400"/><div><p className="text-[10px] font-black uppercase tracking-wider text-emerald-300">{t('Informe de Puesta en Servicio BESS','BESS Commissioning Report')}</p><h2 className="mt-1 text-lg font-bold text-white">{t('Snapshot determinístico de Puesta en Servicio','Deterministic commissioning snapshot')}</h2><p className="mt-2 text-xs leading-relaxed text-gray-400">{t('Construye un informe local y trazable desde el snapshot almacenado o cargado explícitamente. Generarlo no ejecuta pruebas, cambia aceptación, cierra Pendientes ni escribe en sistemas OT.','Build a local, traceable report from the stored or explicitly loaded Commissioning snapshot. Report generation does not execute tests, change acceptance, close Punch Items or write to OT systems.')}</p></div></div><span className="rounded border border-cyan-500/20 bg-cyan-500/10 px-3 py-2 text-[10px] font-black text-cyan-300">{t('SOLO LECTURA · MODO SOMBRA','READ-ONLY SHADOW MODE')}</span></div></header>
  <div className="grid grid-cols-1 gap-4 lg:grid-cols-[1fr_1fr_auto]"><label className="text-[10px] font-bold uppercase tracking-wider text-gray-500">{t('Proyecto','Project')}<select value={projectId} onChange={e=>handleProjectChange(e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-gray-800 bg-gray-950 px-3 text-xs text-gray-200">{state.snapshot.projects.map(p=><option key={p.projectId} value={p.projectId}>{p.name}</option>)}</select></label><label className="text-[10px] font-bold uppercase tracking-wider text-gray-500">{t('Alcance','Scope')}<select value={scopeId} onChange={e=>{setScopeId(e.target.value);setReport(null);setMessage('')}} className="mt-1 min-h-11 w-full rounded-lg border border-gray-800 bg-gray-950 px-3 text-xs text-gray-200">{scopes.map(s=><option key={s.scopeId} value={s.scopeId}>{s.name} · {t('rev','rev')} {s.revision}</option>)}</select></label><div className="flex items-end gap-2"><button type="button" onClick={refreshStored} title={t('Refrescar datos almacenados','Refresh stored commissioning data')} className="min-h-11 rounded-lg border border-gray-700 bg-gray-950 px-3"><RefreshCw className="h-4 w-4"/></button><button type="button" onClick={generateReport} disabled={!projectId||!scopeId} className="min-h-11 rounded-lg bg-emerald-500 px-4 text-xs font-extrabold text-slate-950">{t('Generar informe','Generate report')}</button></div></div>
  {message?<div className="rounded-lg border border-gray-800 bg-gray-950 px-3 py-2 text-[10px] text-gray-400">{message}</div>:null}
  {report?<div className="space-y-4"><section className="grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-8" aria-label={t('Resumen del informe','Commissioning report summary')}>{[[t('Activos en alcance','Assets in scope'),report.summary.assetsInScope],[t('Ejecuciones','Executions'),report.summary.testExecutions],['ORBI '+t('CUMPLE','PASS'),report.summary.executionAssessmentCounts.PASS],[t('Anomalías activas','Active anomalies'),report.summary.anomalies.active],[t('Hallazgos abiertos','Open findings'),report.summary.findings.open],[t('Pendientes abiertos','Open Punch'),report.summary.punchItems.open],[t('Evidencias','Evidence'),report.summary.evidenceRecords],[t('Entrega','Handover'),report.handover?canonical(report.handover.status):t('NINGUNA','NONE')]].map(([l,v])=><article key={String(l)} className="rounded-xl border border-gray-800 bg-gray-950 p-4"><p className="text-[9px] font-black uppercase text-gray-500">{l}</p><p className="mt-2 text-xl font-black text-white">{v}</p></article>)}</section>
   <div className="grid grid-cols-1 gap-4 xl:grid-cols-2"><article className="rounded-xl border border-gray-800 bg-gray-950 p-5"><p className="text-[9px] font-black uppercase tracking-wider text-gray-500">{t('Identidad del informe','Report identity')}</p><h3 className="mt-2 text-sm font-bold text-white">{report.project.name}</h3><p className="mt-2 text-xs text-gray-400">{report.scope.name} · {t('rev','rev')} {report.scope.revision}</p><div className="mt-3 grid grid-cols-2 gap-2 text-[10px]"><div><p className="text-gray-600">{t('Generado','Generated')}</p><p className="mt-1 font-mono text-gray-400">{report.generatedAt}</p></div><div><p className="text-gray-600">{t('Modo','Mode')}</p><p className="mt-1 font-black text-cyan-300">{t('SOLO LECTURA / MODO SOMBRA',report.mode)}</p></div><div><p className="text-gray-600">{t('Línea base','Baseline')}</p><p className="mt-1 font-mono text-gray-400">{report.baseline?.baselineId??t('NINGUNA','NONE')}</p></div><div><p className="text-gray-600">{t('Entrega','Handover')}</p><p className="mt-1 font-mono text-gray-400">{report.handover?.handoverPackageId??t('NINGUNA','NONE')}</p></div></div></article><article className="rounded-xl border border-gray-800 bg-gray-950 p-5"><p className="text-[9px] font-black uppercase tracking-wider text-gray-500">{t('Paquete de trazabilidad','Traceability package')}</p><div className="mt-3 grid grid-cols-2 gap-2 text-[10px]"><div>{t('IDs de anomalías','Anomaly IDs')}: <b>{report.traceability.anomalyIds.length}</b></div><div>{t('IDs de hallazgos','Finding IDs')}: <b>{report.traceability.findingIds.length}</b></div><div>{t('IDs de pendientes','Punch IDs')}: <b>{report.traceability.punchItemIds.length}</b></div><div>{t('Decisiones de aceptación','Acceptance decisions')}: <b>{report.traceability.humanAcceptanceDecisionIds.length}</b></div></div></article></div>
   <div className="flex flex-wrap gap-2"><button type="button" onClick={exportText} className="min-h-11 rounded-lg border border-gray-700 bg-gray-950 px-4 text-xs font-bold text-gray-200"><Download className="mr-2 inline h-3.5 w-3.5"/>{t('Exportar TXT','Export TXT')}</button><button type="button" onClick={exportJson} className="min-h-11 rounded-lg border border-gray-700 bg-gray-950 px-4 text-xs font-bold text-gray-200"><Download className="mr-2 inline h-3.5 w-3.5"/>{t('Exportar JSON','Export JSON')}</button></div>
   <div className="rounded-lg border border-amber-500/15 bg-amber-500/5 p-3"><div className="flex items-center gap-2"><ShieldCheck className="h-3.5 w-3.5 text-amber-300"/><p className="text-[9px] font-black uppercase tracking-wider text-amber-300">{t('Límite de autoridad','Authority boundary')}</p></div><div className="mt-2 space-y-1">{localizedLimitations.map(l=><p key={l} className="text-[10px] leading-relaxed text-gray-300">• {l}</p>)}</div></div>
  </div>:<div className="rounded-xl border border-dashed border-gray-700 bg-gray-950 p-8 text-center"><FileText className="mx-auto h-7 w-7 text-gray-600"/><p className="mt-3 text-sm font-semibold text-gray-300">{t('Selecciona proyecto y alcance y luego genera un informe snapshot.','Select project and scope, then generate a snapshot report.')}</p><p className="mx-auto mt-2 max-w-xl text-xs text-gray-500">{t('La generación es local y explícita. El informe no constituye una decisión de aceptación de Puesta en Servicio.','Generation is local and explicit. The report is not a commissioning acceptance decision.')}</p></div>}
 </section>;
};