import React, { useMemo, useState } from 'react';
import { ClipboardCheck, Link2, RotateCcw, Search, ShieldCheck } from 'lucide-react';
import type { CommissioningWorkspaceState } from '../application/commissioningService';
import type { CommissioningAsset, CommissioningBaseline, Finding, TestExecution } from '../contracts';
import { useCommissioningI18n } from '../localization/CommissioningLocaleContext';

type BaselineStatus = CommissioningBaseline['status'];
type StatusFilter = 'ALL' | BaselineStatus;
const statusClass: Record<BaselineStatus,string>={DRAFT:'border-gray-700 bg-gray-900 text-gray-300',AVAILABLE:'border-emerald-500/25 bg-emerald-500/10 text-emerald-300',SUPERSEDED:'border-amber-500/25 bg-amber-500/10 text-amber-300'};

export const CommissioningBaselineView:React.FC<{state:CommissioningWorkspaceState}>=({state})=>{
 const i18n=useCommissioningI18n(); const t=i18n.text; const snapshot=state.snapshot; const baselines=snapshot.baselines; const [statusFilter,setStatusFilter]=useState<StatusFilter>('ALL'); const [query,setQuery]=useState('');
 const formatMetricValue=(value:number|string|boolean|null,unit?:string):string=>{if(value===null)return 'NULL'; const rendered=typeof value==='boolean'?(value?t('VERDADERO','TRUE'):t('FALSO','FALSE')):String(value); return unit?`${rendered} ${unit}`:rendered;};
 const assetById=useMemo(()=>new Map<string,CommissioningAsset>(snapshot.assets.map((asset):[string,CommissioningAsset]=>[asset.assetId,asset])),[snapshot.assets]);
 const executionById=useMemo(()=>new Map<string,TestExecution>(snapshot.testExecutions.map((execution):[string,TestExecution]=>[execution.executionId,execution])),[snapshot.testExecutions]);
 const findingById=useMemo(()=>new Map<string,Finding>(snapshot.findings.map((finding):[string,Finding]=>[finding.findingId,finding])),[snapshot.findings]);
 const filtered=useMemo(()=>{const normalized=query.trim().toLowerCase(); return baselines.filter((baseline)=>{if(statusFilter!=='ALL'&&baseline.status!==statusFilter)return false;if(!normalized)return true;const asset=assetById.get(baseline.assetId);return [baseline.baselineId,baseline.revision,baseline.status,baseline.acceptedBy,asset?.name,...baseline.metrics.map((metric)=>metric.metricKey),...baseline.configurationReferences,...baseline.knownDeviationFindingIds].filter(Boolean).some((value)=>String(value).toLowerCase().includes(normalized));});},[assetById,baselines,query,statusFilter]);
 if(baselines.length===0)return <div className="space-y-5" id="commissioning-baseline-view"><div><p className="text-[10px] font-black uppercase tracking-wider text-gray-500">{t('Línea Base','Baseline')}</p><h2 className="mt-1 text-lg font-bold text-white">{t('No hay línea base de Puesta en Servicio cargada','No commissioning baseline loaded')}</h2></div><div className="rounded-xl border border-dashed border-gray-700 bg-gray-950 p-8 text-center"><ClipboardCheck className="mx-auto h-8 w-8 text-gray-600"/><p className="mt-3 text-sm font-semibold text-gray-200">{t('El snapshot actual no contiene un artefacto de línea base aceptado.','The current snapshot contains no accepted baseline artifact.')}</p><p className="mx-auto mt-2 max-w-2xl text-xs leading-relaxed text-gray-500">{t('Una línea base de Puesta en Servicio solo es válida cuando se construye con métricas de una ejecución ORBI CUMPLE con aceptación humana explícita. Los datos faltantes permanecen faltantes y no se infieren desde valores de monitoreo.','A commissioning baseline is valid only when it is built from metrics belonging to an ORBI PASS execution with explicit human acceptance. Missing baseline data remains missing and must not be inferred from monitoring values.')}</p></div></div>;
 const availableCount=baselines.filter((b)=>b.status==='AVAILABLE').length,draftCount=baselines.filter((b)=>b.status==='DRAFT').length,supersededCount=baselines.filter((b)=>b.status==='SUPERSEDED').length,metricCount=baselines.reduce((s,b)=>s+b.metrics.length,0),withDeviationsCount=baselines.filter((b)=>b.knownDeviationFindingIds.length>0).length;
 return <div className="space-y-5" id="commissioning-baseline-view">
  <div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-black uppercase tracking-wider text-gray-500">{t('Línea Base','Baseline')}</p><h2 className="mt-1 text-lg font-bold text-white">{t('Referencia aceptada de Puesta en Servicio','Accepted commissioning reference')}</h2><p className="mt-1 text-xs text-gray-500">{t('Métricas de referencia almacenadas con procedencia de ejecución, revisión aceptada, contexto de configuración y desviaciones conocidas.','Stored reference metrics with execution provenance, accepted revision, configuration context and known deviations.')}</p></div><div className="rounded-lg border border-emerald-500/15 bg-emerald-500/5 px-3 py-2 text-[10px] font-semibold text-emerald-200">{t('SOLO LECTURA · SOLO FUENTES CUMPLE ACEPTADAS · PRECEDENCIA DE REPRUEBA CONSERVADA','READ-ONLY · ACCEPTED PASS SOURCES ONLY · RETEST PRECEDENCE PRESERVED')}</div></div>
  <section className="grid grid-cols-2 gap-3 md:grid-cols-6" aria-label={t('Resumen de línea base','Baseline summary')}>{[[t('Total','Total'),baselines.length],[t('Disponibles','Available'),availableCount],[t('Borrador','Draft'),draftCount],[t('Reemplazadas','Superseded'),supersededCount],[t('Métricas','Metrics'),metricCount],[t('Con desviaciones','With deviations'),withDeviationsCount]].map(([label,value])=><article key={String(label)} className="rounded-xl border border-gray-800 bg-gray-950 p-4"><p className="text-[9px] font-black uppercase text-gray-500">{label}</p><p className="mt-2 text-2xl font-black text-white">{value}</p></article>)}</section>
  <section className="grid grid-cols-1 gap-3 lg:grid-cols-[1fr_auto]" aria-label={t('Filtros de línea base','Baseline filters')}><label className="relative block"><span className="sr-only">{t('Buscar líneas base','Search baselines')}</span><Search className="pointer-events-none absolute left-3 top-3.5 h-4 w-4 text-gray-600"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder={t('Buscar línea base, revisión, activo, métrica, configuración o desviación','Search baseline, revision, asset, metric, configuration or deviation')} className="min-h-11 w-full rounded-lg border border-gray-800 bg-gray-950 pl-10 pr-3 text-xs text-gray-200"/></label><label className="text-[9px] font-bold uppercase tracking-wider text-gray-500">{t('Estado','Status')}<select value={statusFilter} onChange={(e)=>setStatusFilter(e.target.value as StatusFilter)} className="ml-2 min-h-11 rounded-lg border border-gray-800 bg-gray-950 px-3 text-xs text-gray-200"><option value="ALL">{t('Todas las líneas base','All baselines')}</option>{(['AVAILABLE','DRAFT','SUPERSEDED'] as BaselineStatus[]).map(v=><option key={v} value={v}>{i18n.canonical(v)}</option>)}</select></label></section>
  {filtered.length===0?<div className="rounded-xl border border-dashed border-gray-700 bg-gray-950 p-8 text-center text-xs text-gray-500">{t('Ninguna línea base coincide con los filtros actuales.','No baselines match the current filters.')}</div>:<div className="space-y-4">{filtered.map((baseline)=>{const asset=assetById.get(baseline.assetId);return <article key={baseline.baselineId} className="rounded-xl border border-gray-800 bg-gray-950 p-5"><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={`rounded border px-2 py-1 text-[9px] font-black ${statusClass[baseline.status]}`}>{i18n.canonical(baseline.status)}</span><span className="rounded border border-gray-700 bg-gray-900 px-2 py-1 text-[9px] font-bold text-gray-300">REV · {baseline.revision}</span></div><h3 className="mt-3 text-sm font-bold text-white">{asset?.name??baseline.assetId}</h3><p className="mt-2 text-xs text-gray-500">{t('Aceptada por','Accepted by')} <span className="font-semibold text-gray-300">{baseline.acceptedBy}</span> {t('el','at')} <span className="font-mono text-gray-400">{baseline.acceptedAt}</span></p></div><p className="shrink-0 font-mono text-[9px] text-gray-600">{baseline.baselineId}</p></div>
   <div className="mt-4 grid grid-cols-2 gap-2 md:grid-cols-4 xl:grid-cols-6 text-[10px]"><div className="rounded-lg border border-gray-800 bg-gray-900 p-3"><p className="text-gray-600">{t('Proyecto','Project')}</p><p className="mt-1 break-all font-mono text-gray-400">{baseline.projectId}</p></div><div className="rounded-lg border border-gray-800 bg-gray-900 p-3"><p className="text-gray-600">{t('Alcance','Scope')}</p><p className="mt-1 break-all font-mono text-gray-400">{baseline.scopeId}</p></div><div className="rounded-lg border border-cyan-500/15 bg-cyan-500/5 p-3"><p className="text-cyan-300">{t('Métricas','Metrics')}</p><p className="mt-1 text-lg font-bold text-white">{baseline.metrics.length}</p></div><div className="rounded-lg border border-violet-500/15 bg-violet-500/5 p-3"><p className="text-violet-300">{t('Entradas de firmware','Firmware entries')}</p><p className="mt-1 text-lg font-bold text-white">{Object.keys(baseline.firmwareVersions).length}</p></div><div className="rounded-lg border border-gray-800 bg-gray-900 p-3"><p className="text-gray-600">{t('Refs. configuración','Config refs')}</p><p className="mt-1 text-lg font-bold text-white">{baseline.configurationReferences.length}</p></div><div className="rounded-lg border border-gray-800 bg-gray-900 p-3"><p className="text-gray-600">{t('Desviaciones conocidas','Known deviations')}</p><p className="mt-1 text-lg font-bold text-white">{baseline.knownDeviationFindingIds.length}</p></div></div>
   <div className="mt-4 overflow-x-auto rounded-lg border border-gray-800"><table className="min-w-full text-left text-[10px]"><caption className="sr-only">{t('Métricas de línea base aceptadas y ejecuciones de origen','Accepted baseline metrics and source executions')}</caption><thead className="bg-gray-900 text-gray-500"><tr><th className="px-3 py-2">{t('Métrica','Metric')}</th><th className="px-3 py-2">{t('Valor','Value')}</th><th className="px-3 py-2">{t('Ejecución de origen','Source execution')}</th><th className="px-3 py-2">{t('Tipo','Type')}</th><th className="px-3 py-2">ORBI</th><th className="px-3 py-2">{t('Humano','Human')}</th><th className="px-3 py-2">{t('Cálculo','Calculation')}</th></tr></thead><tbody>{baseline.metrics.map((metric)=>{const execution=executionById.get(metric.sourceExecutionId),isRetest=execution?.executionType==='RETEST';return <tr key={`${baseline.baselineId}:${metric.metricKey}`} className="border-t border-gray-800"><td className="px-3 py-3 font-semibold">{metric.metricKey}</td><td className="px-3 py-3 font-mono">{formatMetricValue(metric.value,metric.unit)}</td><td className="px-3 py-3 font-mono text-gray-500">{metric.sourceExecutionId}</td><td className="px-3 py-3">{execution?<span className={isRetest?'text-violet-300':'text-gray-300'}>{isRetest?<RotateCcw className="mr-1 inline h-3 w-3"/>:null}{i18n.canonical(execution.executionType)}{isRetest?` · ${t('PRECEDENCIA','PRECEDENCE')}`:''}</span>:<span className="text-amber-300">{i18n.notLoaded}</span>}</td><td className="px-3 py-3 font-black">{execution?i18n.canonical(execution.orbiAssessment):i18n.notLoaded}</td><td className="px-3 py-3 font-black">{execution?i18n.canonical(execution.humanAcceptance):i18n.notLoaded}</td><td className="px-3 py-3 font-mono text-gray-500">{metric.calculationId??i18n.notRecorded}</td></tr>})}</tbody></table></div>
   <div className="mt-4 grid grid-cols-1 gap-3 xl:grid-cols-3"><div className="rounded-lg border border-gray-800 bg-gray-900 p-3"><p className="text-[9px] font-black uppercase tracking-wider text-gray-600">{t('Versiones de firmware','Firmware versions')}</p>{Object.keys(baseline.firmwareVersions).length===0?<p className="mt-2 text-[10px] text-gray-500">{t('No hay versiones de firmware registradas.','No firmware versions recorded.')}</p>:Object.entries(baseline.firmwareVersions).map(([k,v])=><p key={k} className="mt-2 text-[10px] text-gray-400"><b>{k}</b> · {v}</p>)}</div><div className="rounded-lg border border-gray-800 bg-gray-900 p-3"><div className="flex items-center gap-2"><Link2 className="h-3.5 w-3.5 text-cyan-400"/><p className="text-[9px] font-black uppercase tracking-wider text-gray-600">{t('Referencias de configuración','Configuration references')}</p></div>{baseline.configurationReferences.length===0?<p className="mt-2 text-[10px] text-gray-500">{t('No hay referencias de configuración registradas.','No configuration references recorded.')}</p>:baseline.configurationReferences.map(r=><p key={r} className="mt-2 break-all text-[10px] text-gray-400">{r}</p>)}</div><div className="rounded-lg border border-gray-800 bg-gray-900 p-3"><p className="text-[9px] font-black uppercase tracking-wider text-gray-600">{t('Desviaciones conocidas','Known deviations')}</p>{baseline.knownDeviationFindingIds.length===0?<p className="mt-2 text-[10px] text-gray-500">{t('No hay IDs de Hallazgos por desviación conocidos.','No known deviation Finding IDs recorded.')}</p>:baseline.knownDeviationFindingIds.map(id=>{const finding=findingById.get(id);return <div key={id} className="mt-2 rounded border border-orange-500/10 bg-gray-950 p-2 text-[10px]"><p className="font-mono text-orange-300">{id}</p><p className="mt-1 text-gray-300">{finding?.title??t('Hallazgo no cargado en este snapshot.','Finding not loaded in this snapshot.')}</p></div>})}</div></div>
  </article>})}</div>}
  <div className="rounded-lg border border-gray-800 bg-gray-950 px-3 py-2 text-[10px] leading-relaxed text-gray-500"><ShieldCheck className="mr-1 inline h-3.5 w-3.5 text-emerald-400"/>{t('Una línea base almacenada como DISPONIBLE es un artefacto de referencia de Puesta en Servicio, no una aprobación global de entrega ni una autorización para energizar u operar equipos. Cuando existen cálculos iniciales y de reprueba aceptados para la misma métrica, el Core da precedencia a la fuente de reprueba.','A stored AVAILABLE baseline is a commissioning reference artifact, not a global handover approval and not an authorization to energize or operate equipment. When both accepted initial and accepted retest calculations exist for the same metric, the Core gives precedence to the retest source.')}</div>
 </div>;
};