export type ClimateRecoveryLocale = 'es' | 'en';

const copy = {
  es: {
    product: 'ORBI PVMetrics IA',
    edition: 'Climate Recovery Edition',
    demonstration: 'Demostración sintética',
    title: 'Recuperación Climática',
    subtitle: 'Inteligencia operacional asistida por IA para identificar y priorizar pérdidas recuperables de energía renovable.',
    disclosure: 'Todos los activos, casos y resultados de esta vista son sintéticos y se presentan exclusivamente con fines demostrativos.',
    syntheticDisclosureLabel: 'Divulgación de datos sintéticos',
    operatorBoundary: 'Soporte de decisión — no es una orden operacional. La persona operadora conserva la decisión final.',
    evaluated: 'Evaluado',
    language: 'Idioma',
    readOnly: 'Solo lectura',
    noNetwork: 'Sin red',
    safetyFooter: 'Sin credenciales · sin despacho · sin impacto verificado',
    back: 'Volver al dashboard general',
    freeExplore: 'Exploración libre',
    guidedDemo: 'Demo guiada',
    startGuidedDemo: 'Iniciar demo guiada',
    guidedDemoDescription: 'Recorrido competitivo controlado de ocho pasos. Sin reproducción automática.',
    exitDemo: 'Salir de la demo',
    resetDemo: 'Reiniciar demo',
    returnOverview: 'Volver al resumen',
    previous: 'Anterior',
    next: 'Siguiente',
    skip: 'Omitir',
    step: 'Paso',
    of: 'de',
    keyPoints: 'Puntos clave',
    narration: 'Narrativa',
    durationHint: 'Duración sugerida',
    overview: 'Resumen',
    plants: 'Plantas',
    opportunities: 'Oportunidades',
    review: 'Revisión humana',
    syntheticAssets: 'Activos sintéticos',
    activeCases: 'Casos de recuperación',
    recoverableEnergy: 'Energía recuperable estimada',
    avoidedEmissions: 'Emisiones evitadas estimadas',
    pendingReview: 'Revisión humana pendiente',
    opportunityScore: 'Climate Opportunity Score',
    scoreTooltip: 'Índice interno transparente de demostración. No es una probabilidad ni una métrica certificada.',
    plantRanking: 'Ranking de plantas',
    recoverability: 'Distribución de recuperabilidad',
    priority: 'Distribución de prioridad',
    dataQuality: 'Calidad de datos',
    asset: 'Activo',
    highPriority: 'Alta prioridad',
    highestPriority: 'Prioridad más alta',
    overlapPenalty: 'Penalización por solapamiento',
    overlapNotice: 'Las penalizaciones por solapamiento permanecen visibles según el contrato CR-04.',
    featured: 'Oportunidades destacadas',
    featuredDescription: 'La evidencia sugiere oportunidades potenciales; cada caso requiere revisión humana.',
    inspectCase: 'Inspeccionar caso',
    viewPlant: 'Ver planta',
    allCases: 'Los 14 casos sintéticos',
    filters: 'Filtros locales',
    noResults: 'Ningún caso coincide con los filtros seleccionados.',
    clearFilters: 'Limpiar filtros',
    case: 'Caso',
    plant: 'Planta',
    category: 'Categoría',
    confidence: 'Confianza',
    dataSufficiency: 'Suficiencia de datos',
    estimatedEnergy: 'Energía estimada',
    climateImpact: 'Impacto climático',
    climateAvailability: 'Disponibilidad climática',
    recommendedAction: 'Siguiente paso recomendado',
    humanReviewQueue: 'Cola de revisión humana',
    queueNotice: 'Esta es una cola de revisión sintética. No se ejecuta ningún flujo operacional.',
    evidenceGap: 'Brecha de evidencia',
    reviewType: 'Tipo de revisión',
    urgency: 'Urgencia',
    inspectEvidence: 'Inspeccionar evidencia',
    inspectMethodology: 'Inspeccionar metodología',
    reason: 'Motivo',
    noEvidenceGap: 'No se registró una brecha explícita.',
    caseSummary: 'Resumen del caso',
    summary: 'Resumen',
    recommendedNextStepTitle: 'Siguiente paso recomendado',
    recoveryScenario: 'Escenario de recuperación',
    technicalDetails: 'Detalles técnicos',
    suppressedActions: 'Acciones suprimidas o no recomendadas',
    suppressedReason: 'Estas acciones se retienen para trazabilidad, pero no se recomiendan bajo la evaluación actual.',
    keyMetrics: 'Métricas clave',
    recoveryOpportunity: 'Oportunidad de recuperación',
    actions: 'Acciones recomendadas',
    scenarios: 'Comparación de escenarios',
    evidence: 'Evidencia',
    hypotheses: 'Hipótesis',
    timeline: 'Línea de tiempo',
    why: '¿Por qué este resultado?',
    assumptions: 'Supuestos',
    limitations: 'Limitaciones',
    supporting: 'A favor',
    contradicting: 'Contradictoria',
    neutral: 'Neutral',
    missing: 'Faltante / no disponible',
    noIntervention: 'Sin intervención',
    withIntervention: 'Con intervención',
    projectedRecovery: 'Recuperación estimada',
    scenarioDisclosure: 'Proyecciones simuladas de CR-03; no se promete recuperación.',
    scenarioTable: 'Comparación accesible del escenario',
    horizon: 'Horizonte',
    recoveryRate: 'Supuesto de tasa de recuperación',
    uncertainty: 'Incertidumbre',
    showMore: 'Mostrar más',
    showLess: 'Mostrar menos',
    unavailable: 'No disponible',
    blocked: 'Bloqueado',
    pending: 'Pendiente de revisión',
    notApplicable: 'No aplica',
    estimated: 'Estimado',
    projected: 'Proyectado',
    scoreDisclaimer: 'Confidence es una evaluación cualitativa interna, no una probabilidad calibrada.',
    plantPortfolio: 'Portafolio de cinco plantas sintéticas',
    capacity: 'Capacidad',
    cases: 'Casos',
    region: 'Región genérica',
    warnings: 'Advertencias',
    methodology: 'Metodología',
    factor: 'Factor de emisión sintético',
    verification: 'Estado de verificación',
    notVerified: 'No verificado',
    recoveryStates: 'Estados de recuperación',
    inspect: 'Inspeccionar',
    all: 'Todos',
    sort: 'Ordenar',
    required: 'Requerida',
    notRequired: 'No requerida',
    approvalRequired: 'Aprobación requerida',
    safetyAndUncertainty: 'Seguridad e incertidumbre',
    actionType: 'Tipo de acción',
    expectedOutcome: 'Resultado esperado',
    source: 'Fuente',
    notDiagnosis: 'No es un diagnóstico confirmado.',
    hypothesesBoundary: 'Las hipótesis son generadas por reglas y permanecen sin confirmar.',
    stableTimeline: 'Timestamps estables de CR-03; no se inventan eventos con la hora actual.',
    appliedRules: 'Reglas aplicadas',
    confidenceExplanation: 'Explicación de confianza',
    noneDocumented: 'Ninguno documentado.',
    caseNotFound: 'Caso no encontrado',
    counterfactual: 'Estimación contrafactual',
    plantDistributions: 'Distribuciones de la planta',
    reviewStatus: 'Estado de revisión',
    featuredCase: 'Caso destacado',
    detailsAndLimitations: 'Advertencias y limitaciones',
    syntheticChartDisclosure: 'Resumen sintético para demostración; no es una medición operacional.',
    rankingCaption: 'Ranking de cinco plantas sintéticas por Climate Opportunity Score, con energía, impacto, calidad y revisión.',
    opportunitiesCaption: 'Catorce oportunidades sintéticas con recuperabilidad, prioridad, suficiencia de datos y revisión humana.',
    statusLabels: {
      critical: 'Crítica', high: 'Alta', medium: 'Media', low: 'Baja', informational: 'Informativa',
      recoverable: 'Recuperable', 'partially-recoverable': 'Parcialmente recuperable', 'non-recoverable': 'No recuperable', indeterminate: 'Indeterminada', 'not-assessed': 'No evaluada',
      sufficient: 'Suficiente', 'partially-sufficient': 'Parcialmente suficiente', insufficient: 'Insuficiente', invalid: 'Inválida',
      available: 'Disponible', unavailable: 'No disponible', blocked: 'Bloqueada', 'not-applicable': 'No aplica', 'pending-review': 'Pendiente de revisión',
      valid: 'Válida', degraded: 'Degradada', incomplete: 'Incompleta', stale: 'Obsoleta', conflicting: 'En conflicto', unknown: 'Desconocida',
      warning: 'Advertencia', caution: 'Precaución', neutral: 'Neutral', informative: 'Informativa', positive: 'Positiva',
      minimal: 'Mínima', moderate: 'Moderada', 'very-high': 'Muy alta',
    },
  },
  en: {
    product: 'ORBI PVMetrics IA',
    edition: 'Climate Recovery Edition',
    demonstration: 'Synthetic Demonstration',
    title: 'Climate Recovery',
    subtitle: 'AI-assisted operational intelligence for identifying and prioritizing recoverable renewable-energy losses.',
    disclosure: 'All assets, cases, and results in this view are synthetic and presented exclusively for demonstration purposes.',
    syntheticDisclosureLabel: 'Synthetic data disclosure',
    operatorBoundary: 'Decision support — not an operational order. The operator retains the final decision.',
    evaluated: 'Evaluated',
    language: 'Language',
    readOnly: 'Read-only',
    noNetwork: 'No network',
    safetyFooter: 'No credentials · no dispatch · no verified impact',
    back: 'Back to general dashboard',
    freeExplore: 'Free Explore',
    guidedDemo: 'Guided Demo',
    startGuidedDemo: 'Start guided demo',
    guidedDemoDescription: 'Controlled eight-step competition flow. No autoplay.',
    exitDemo: 'Exit Demo',
    resetDemo: 'Reset Demo',
    returnOverview: 'Return to Overview',
    previous: 'Previous',
    next: 'Next',
    skip: 'Skip',
    step: 'Step',
    of: 'of',
    keyPoints: 'Key Points',
    narration: 'Narrative',
    durationHint: 'Suggested duration',
    overview: 'Overview',
    plants: 'Plants',
    opportunities: 'Opportunities',
    review: 'Human Review',
    syntheticAssets: 'Synthetic Assets',
    activeCases: 'Active Recovery Cases',
    recoverableEnergy: 'Estimated Recoverable Energy',
    avoidedEmissions: 'Estimated Avoided Emissions',
    pendingReview: 'Pending Human Review',
    opportunityScore: 'Climate Opportunity Score',
    scoreTooltip: 'Internal transparent demo index. Not a probability or certified metric.',
    plantRanking: 'Plant Ranking',
    recoverability: 'Recoverability Distribution',
    priority: 'Priority Distribution',
    dataQuality: 'Data Quality Overview',
    asset: 'Asset',
    highPriority: 'High Priority',
    highestPriority: 'Highest Priority',
    overlapPenalty: 'Overlap Penalty',
    overlapNotice: 'Overlap penalties remain visible under the CR-04 contract.',
    featured: 'Featured Opportunities',
    featuredDescription: 'Evidence suggests potential opportunities; every case requires human review.',
    inspectCase: 'Inspect Case',
    viewPlant: 'View Plant',
    allCases: 'All 14 synthetic cases',
    filters: 'Local filters',
    noResults: 'No cases match the selected filters.',
    clearFilters: 'Clear filters',
    case: 'Case',
    plant: 'Plant',
    category: 'Category',
    confidence: 'Confidence',
    dataSufficiency: 'Data Sufficiency',
    estimatedEnergy: 'Estimated Energy',
    climateImpact: 'Climate Impact',
    climateAvailability: 'Climate Availability',
    recommendedAction: 'Recommended Next Step',
    humanReviewQueue: 'Human Review Queue',
    queueNotice: 'This is a synthetic review queue. No operational workflow is executed.',
    evidenceGap: 'Evidence Gap',
    reviewType: 'Review Type',
    urgency: 'Urgency',
    inspectEvidence: 'Inspect Evidence',
    inspectMethodology: 'Inspect Methodology',
    reason: 'Reason',
    noEvidenceGap: 'No explicit gap recorded.',
    caseSummary: 'Case Summary',
    summary: 'Summary',
    recommendedNextStepTitle: 'Recommended Next Step',
    recoveryScenario: 'Recovery Scenario',
    technicalDetails: 'Technical Details',
    suppressedActions: 'Suppressed or Not Recommended Actions',
    suppressedReason: 'These actions are retained for traceability but are not recommended under the current assessment.',
    keyMetrics: 'Key Metrics',
    recoveryOpportunity: 'Recovery Opportunity',
    actions: 'Recommended Actions',
    scenarios: 'Scenario Comparison',
    evidence: 'Evidence',
    hypotheses: 'Hypotheses',
    timeline: 'Timeline',
    why: 'Why this result?',
    assumptions: 'Assumptions',
    limitations: 'Limitations',
    supporting: 'Supporting',
    contradicting: 'Contradicting',
    neutral: 'Neutral',
    missing: 'Missing / Unavailable',
    noIntervention: 'No Intervention',
    withIntervention: 'With Intervention',
    projectedRecovery: 'Estimated Recovered Energy',
    scenarioDisclosure: 'Simulated projections from CR-03; no recovery is promised.',
    scenarioTable: 'Accessible scenario comparison',
    horizon: 'Horizon',
    recoveryRate: 'Recovery Rate Assumption',
    uncertainty: 'Uncertainty',
    showMore: 'Show more',
    showLess: 'Show less',
    unavailable: 'Unavailable',
    blocked: 'Blocked',
    pending: 'Pending review',
    notApplicable: 'Not applicable',
    estimated: 'Estimated',
    projected: 'Projected',
    scoreDisclaimer: 'Confidence is an internal qualitative assessment, not a calibrated probability.',
    plantPortfolio: 'Five-plant synthetic portfolio',
    capacity: 'Capacity',
    cases: 'Cases',
    region: 'Generic region',
    warnings: 'Warnings',
    methodology: 'Methodology',
    factor: 'Synthetic emission factor',
    verification: 'Verification status',
    notVerified: 'Not verified',
    recoveryStates: 'Recovery states',
    inspect: 'Inspect',
    all: 'All',
    sort: 'Sort',
    required: 'Required',
    notRequired: 'Not required',
    approvalRequired: 'Approval required',
    safetyAndUncertainty: 'Safety & uncertainty',
    actionType: 'Action Type',
    expectedOutcome: 'Expected Outcome',
    source: 'Source',
    notDiagnosis: 'Not a confirmed diagnosis.',
    hypothesesBoundary: 'Hypotheses are rule-generated and remain unconfirmed.',
    stableTimeline: 'Stable CR-03 timestamps; no current-time events are invented.',
    appliedRules: 'Applied Rules',
    confidenceExplanation: 'Confidence Explanation',
    noneDocumented: 'None documented.',
    caseNotFound: 'Case not found',
    counterfactual: 'Counterfactual Estimate',
    plantDistributions: 'Plant Distributions',
    reviewStatus: 'Review Status',
    featuredCase: 'Featured Case',
    detailsAndLimitations: 'Warnings and Limitations',
    syntheticChartDisclosure: 'Synthetic demonstration summary; not an operational measurement.',
    rankingCaption: 'Ranking of five synthetic plants by Climate Opportunity Score, including energy, impact, quality, and review.',
    opportunitiesCaption: 'Fourteen synthetic opportunities with recoverability, priority, data sufficiency, and human review.',
    statusLabels: {
      critical: 'Critical', high: 'High', medium: 'Medium', low: 'Low', informational: 'Informational',
      recoverable: 'Recoverable', 'partially-recoverable': 'Partially Recoverable', 'non-recoverable': 'Non-recoverable', indeterminate: 'Indeterminate', 'not-assessed': 'Not assessed',
      sufficient: 'Sufficient', 'partially-sufficient': 'Partially sufficient', insufficient: 'Insufficient', invalid: 'Invalid',
      available: 'Available', unavailable: 'Unavailable', blocked: 'Blocked', 'not-applicable': 'Not applicable', 'pending-review': 'Pending review',
      valid: 'Valid', degraded: 'Degraded', incomplete: 'Incomplete', stale: 'Stale', conflicting: 'Conflicting', unknown: 'Unknown',
      warning: 'Warning', caution: 'Caution', neutral: 'Neutral', informative: 'Informative', positive: 'Positive',
      minimal: 'Minimal', moderate: 'Moderate', 'very-high': 'Very high',
    },
  },
} as const;

export type ClimateRecoveryCopy = (typeof copy)[ClimateRecoveryLocale];

export const getClimateRecoveryCopy = (locale: ClimateRecoveryLocale): ClimateRecoveryCopy => copy[locale];
